name: Monorepo
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@jcadiou-bp'
    - run: git config user.name "jcadiou-bp"
    - run: git config user.email "julien.cadiou@beautypie.com"
    - run: yarn
    # - run: yarn test
    - run: yarn build
    - run: yarn packages:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
